"""Init db again

Revision ID: 43636a9785bb
Revises: 
Create Date: 2021-04-29 11:04:58.287271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43636a9785bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.String(length=24), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quatity', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.String(length=16), nullable=False),
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageName', sa.String(length=128), nullable=False),
    sa.Column('pathName', sa.String(length=256), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_product')
    op.drop_table('cart_item')
    op.drop_table('product')
    op.drop_table('cart')
    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###
